{% set version = "2.7" %}

package:
  name: limitcpu
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/limitcpu/files/limitcpu/cpulimit-{{ version }}.tar.gz
  sha256: 1de040a4f8a40dfe8c7a025fe98075673468fbc3fccccbc231bc7402f62ec4a0
  patches:
    - 0001-Fix-__APPLE_-typo.patch

build:
  number: 0
  skip: true  # [win or osx]
  script:
    - make install CFLAGS+=' -DVERSION=$(VERSION)'

requirements:
  build:
    - {{ compiler('c') }}
    - make
  run_constrained:
    # Uses the same "bin/cpulimit" as the "cpulimit" package.
    # => prevent installation alongside the other package.
    - cpulimit <0a0

test:
  commands:
    - '{ cpulimit --help || true ; } | grep -F {{ version }}'
    - cpulimit -vmf -l 100 -- sleep 1
    - '{ sleep 1 & } && cpulimit -vmf -l 100 --pid=$! || [ $? = 2 ]'
    - cpulimit -vm -l 100 --path="$(command -v sleep)" & pid=$! && \sleep 1 && kill $pid && wait $pid

about:
  home: http://limitcpu.sourceforge.net
  dev_url: https://sourceforge.net/projects/limitcpu/
  doc_url: http://limitcpu.sourceforge.net/doc/README
  license: GPL-2.0-only
  license_file: LICENSE
  summary: LimitCPU allows the user to throttle CPU usage of a given process, freeing up the machine to perform other tasks in a timely manner.

extra:
  recipe-maintainers:
    - mbargull
